### ISSUE TITLE
Mapping a key to respawn

### ISSUE THREAD

**Issue by ChickenDipper1** [ItsAmmarB/DeathScript#10]
Hello,

Could you please tell me how to set a default keyboard button to the respawn command?

I have tried to set on this line:

 Respawn: {
            Enabled: true, // Weather is the command enabled, cannot be toggle from in-game
            Keybind: {
                Enabled: true, // Weather the command's keybind is enabled or not, cannot be toggle from in-game
                DefaultKeybind: 'E' // The default keybind, every play can customize it to their own preference

But this does not work.

Any guidance would be much appreciated and thanks for a great script.

**Comment by ItsAmmarB** [comment]
Hey

I've looked at the code and found that the respawn keybind does not work at all, that's because I was too tired when I did it and made it use the revive keybind for both revive and respawn🥲 

I've pushed the fix to the [master branch ](https://github.com/ItsAmmarB/DeathScript/tree/master) and will make it a release in a few minutes.

Thanks you for the feedback 🙏

**Comment by ChickenDipper1** [comment]
That is brilliant, thank you very much for the help :)

**Comment by ItsAmmarB** [comment]
https://github.com/ItsAmmarB/DeathScript/releases/tag/v2.1.4
