### ISSUE TITLE
KEYBINDING ISSUE

### ISSUE THREAD

**Issue by Fivemdev99** [ItsAmmarB/DeathScript#12]
When a player looks left on the controller it will flood the chat with insufficient permissions

**Comment by ItsAmmarB** [comment]
because you've set the keybind to whatever is equivalent to "L3 Left", 
You could set a default keybind of your own choosing in [sh_config.js](https://github.com/ItsAmmarB/DeathScript/blob/master/sh_config.js), each command object has a keybind section with default keybind string, additionally; each player can change the default keybind by going to "Pause menu > settings > keybind > FiveM"

**Comment by Fivemdev99** [comment]
ohh Ok what do i look for in the sh_config.js for that

**Comment by Fivemdev99** [comment]
nevermind about that question. in the script there is nothing for the keybinding section the keybind was left empty for all of them

**Comment by Fivemdev99** [comment]
![image (1)](https://user-images.githubusercontent.com/120705030/208284119-38a8860a-2d9d-4e51-856e-d6939ccc288f.png)

**Comment by Fivemdev99** [comment]
when we go in the game and set a keybind for it, it will still show insufficient Permissions through the chat still when looking left on controller
