### ISSUE TITLE
Breaks vMenu and Esc/map

### ISSUE THREAD

**Issue by GrimaceXX** [ItsAmmarB/DeathScript#15]
I'm unsure of the exact cause as it's only happening to players without the owner tag i my server however when a player dies and they get revived any such way using/ adrev, address, defib, healingpad, etc the vMenu stops working, esc stops working inventory stops only thing they can do is f8 quit. If you'd like to test it out you can reach out to me on discord .grimace#8885 or join discord.gg/chaosgamingnetwork and hmu there as we removed the script for now but really wanna put it back in once fixed. Never had this issue before.

**Comment by ItsAmmarB** [comment]
Hey 😄 

Thank you reaching out to report the bug, and yeah, I will most definitely be reaching out to you to see what is causing that, hopefully tomorrow, as I don't really have much time to debug it today.

**Comment by GrimaceXX** [comment]
> Hey 😄
> 
> Thank you reaching out to report the bug, and yeah, I will most definitely be reaching out to you to see what is causing that, hopefully tomorrow, as I don't really have much time to debug it today.

Sounds good thank you!

**Comment by ItsAmmarB** [comment]
Hey,

Sorry for taking a bit more than what I said,

but; what kind of resources are you running? 
what menus do you have going?
are there any errors in both server and client consoles?
are you running any kind of frameworks that could have any sort of death management systems?
are you suspecting any resource to be conflicting with it? if so, try stopping that resource and try reviving a player, if that behavior persisted try stopping another resource until that behavior is gone.

I'm asking a lot of questions I know, but I've never encountered such behavior, and I'm especially confused because I've made this resource in a public server that I used to run with vMenu and a lot of other resources and custom frameworks.

**Comment by GrimaceXX** [comment]
> Hey,
> 
> Sorry for taking a bit more than what I said,
> 
> but; what kind of resources are you running? what menus do you have going? are there any errors in both server and client consoles? are you running any kind of frameworks that could have any sort of death management systems? are you suspecting any resource to be conflicting with it? if so, try stopping that resource and try reviving a player, if that behavior persisted try stopping another resource until that behavior is gone.
> 
> I'm asking a lot of questions I know, but I've never encountered such behavior, and I'm especially confused because I've made this resource in a public server that I used to run with vMenu and a lot of other resources and custom frameworks.

We are running vMenu and Vehicle Spawner menu
Using NDCore ( it does not have its own death management)
We had every resource stopped except the basic ones to run fivem like spawnmanager and still this was happening. The issue it. It was happening to 6 players out of 7, It does not happen to me.

There are no errors in client or server
The vmenu stops functions, along with all other menus. Ox inventory stops functioning. Esc key doesn't even work. All players can do is press f8 and quit

**Comment by ItsAmmarB** [comment]
what artifact version are you running?

**Comment by GrimaceXX** [comment]
> what artifact version are you running?

We were running an old outdated version with game build 2699 forced when it first started breaking
We updated to the latest artifact and force gamebuild 2802 now and still breaking

**Comment by ItsAmmarB** [comment]
> We updated to the latest artifact

could you give me the exact version number so I can try to reproduce it?

**Comment by GrimaceXX** [comment]
Version 6494

**Comment by GrimaceXX** [comment]
I'll be back online in about 3hours I have to drive to my next pickup. I'll be in the discord if you need me as well

**Comment by ItsAmmarB** [comment]
Hey,

so, I downloaded artifacts v6494, and forced game build to v2802, and used old server files, I had vMenu and vStancer on the server to test it, it worked just fine.

I tried a fresh new server, with a fresh download of the latest vMenu only, it still worked, I tried on an even older test server with old artifacts I had laying around... worked just fine, I tried forcing game build to v2699, works perfectly, tried with 3 people constantly killing each other, nope, still works, I've even got to a point where I was editing the code to intentionally produce something similar to no avail.

at this point, I can only assume it has something to do with your server or perhaps your machine, the script is very lightweight, very minimal and not intrusive, only using natives when needed, and that's what is making my so confused!!

regardless, I'd try a fresh cfx data and artifact download, in a new folder with a fresh copy of vMenu and DeathScript as well, I would also add the other resources one by one just to make sure.

keep me posted on this, I'm intrigued to know what is causing this, also; I want to keep this conversation here, in case the issues isn't caused by this script, and someone else gets this same problem.

![image](https://github.com/ItsAmmarB/DeathScript/assets/13232108/09ff9d4e-c10d-42ba-96aa-81b1746810c1)
![image](https://github.com/ItsAmmarB/DeathScript/assets/13232108/703b4b8c-1bc0-41b5-a71c-f1d91de7a595)

**Comment by GrimaceXX** [comment]
I'm going to have them all reinstall their versions of gta and fivem cause I personally don't have that issue and I game someone the exact same roles as me and they still having the issue. I don't think it's a server or script issue at this point either I'll lyk if it's their version of gta 5

**Comment by GrimaceXX** [comment]
We figured it out. It was caused by a script called bonedev. It's for
vehicle development and well seeing where the bones of each part is for
vehicles.
That script also called the vehicles to go transparent...

**Comment by ItsAmmarB** [comment]
I'm glad you found what is causing that issue, but that's really weird, DeathScript has nothing to do with vehicles or the ped body at all.

is that bonedev script free? and is it in either JS or Lua? if so, would you send it to me on Discord, I'd love to take a look at it and see what is so making it conflict with DeathScript.

**Comment by GrimaceXX** [comment]
It is free and only has client lua file found here
https://forum.cfx.re/t/release-dev-bonedev/347802

**Comment by ItsAmmarB** [comment]
so, 

I've done some testing, and I've also looked into Bonedev's code, there is nothing that would make it break DeathScript, and what even more weird is, it works fine for me!!

https://medal.tv/games/gta-v/clips/1dPN2LZulBWQ1l/d1337GDohzke?invite=cr-MSxkZVosOTMxNzQ2OCw

don't mind the crappy playback fps, I don't know what's wrong with medal

**Comment by GrimaceXX** [comment]
Wee took this script out the same day. Maybe this has something to do with
it

https://github.com/lama-development/HealingPads

**Comment by ItsAmmarB** [comment]
I've just finished testing DeathScript with HealingPeds, nothing seems to be wrong, it's working perfectly..

https://medal.tv/games/gta-v/clips/1dT9IrA9DP1PK5/d1337Wa9Nsic?invite=cr-MSxhdUUsOTMxNzQ2OCw

I feel like this is one of those where your car breaks but once you're at the mechanic shop, it fixes itself lol

**Comment by GrimaceXX** [comment]
Lol ya
